name: Sync to Hugging Face hub
on:
  push:
    branches: [ main ]

    # to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://siying-liu:$HF@huggingface.co/spaces/siying-liu/demo1
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://siying-liu:$HF@huggingface.co/spaces/siying-liu/demo1 main



  # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v3

        # Runs a single command using the runners shell
        - name: Run a one-line script
          run: echo Hello, world!

        # Runs a set of commands using the runners shell
        - name: Run a multi-line script
          run: |
            echo Add other actions to build,
            echo test, and deploy your project.
            
